[package]
name = "med_timer_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
med_timer_shared = { path = "../med_timer_shared" }